version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network
  docker-adonis-api:
    image: docker-adonis-api
    container_name: docker-adonis-api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    # For Windows, we need to enable Chokidar polling so our file changes reflect in real-time.
    environment:
      - CHOKIDAR_USEPOLLING=1
    networks:
      - app-network
    volumes:
      - ./api:/src
      - ./api/node_modules:/src/node_modules
volumes:
  database-data:
  # nodemodules:
networks:
  app-network:
