# app/src volume + chokidar_usepolling is required to work in windows env, i disabled it for faster code reloading.
# if you wish to work in windows env, uncomment them. otherwise attach to running container with vscode.

version: "3"
services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network
  docker-adonis-api:
    image: docker-adonis-api
    container_name: docker-adonis-api
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    # environment:
    # for windows
    # - CHOKIDAR_USEPOLLING=1
    networks:
      - app-network
    # volumes:
    # - ./api:/usr/src/services/api
    # - ./api/node_modules:/src/node_modules
volumes:
  database-data:
  # nodemodules:
networks:
  app-network:
